### ISSUE TITLE
Commented lines in m95xx.c

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/X-CUBE-EEPRMA1#1]
Hello @krt306 
I see some suspicious commented lines in m95xx.c.

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L184-L192

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L267-L275

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L417-L450

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L460-L486

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L493-L498

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L504-L511

They seem really strange, because some of the functions do nothing.
Some others seem a kind of work in progress..
Can you double check, plese?

**Comment by indars** [comment]
Hello,
The commented lines of code is to maintain consistency across different EEPROM expansion boards. The dummy code shall be removed in the next releases.

BR,
Indar

**Comment by mqtdevangelista** [comment]
Hello, I have the same questions that this issue raises. Is it still being worked on and/or is the next release scheduled?

It seems that the current driver results in calls to these functions with all of the functionality commented out, particularly for the M95 driver instances. Can these functions work by uncommenting the code? Am I misunderstanding something and the proper implementations are somewhere else?

For context, I am trying to interface a non-ST microcontroller board with the Nucleo expansion board by referencing this driver and redefining the HAL.

**Comment by tanujlokpal** [comment]
Hello,

The dummy code shall be removed. Further, there is no separate API for page read/write functionality in M95xxx EEPROM. You may use M95_spi_ReadData() / M95_spi_WriteData() functions for reading and writing to memory which is part of our existing BSP driver. Also, we will update M95_spi_ReadPage() / M95_spi_WritePage() API for user application but internally it will call M95_spi_ReadData() / M95_spi_WriteData().

You may refer the following code snippet:

1. M95_spi_ReadPage() will call M95_spi_ReadData()

int32_t M95_spi_ReadPage(M95_Object_t *pObj, uint8_t * pData, const uint32_t TarAddr, const uint16_t PageSize )
{            
  int32_t status = M95_OK;
  
  while( pObj->IO.IsReady( pObj->IO.Address ) != M95_OK ) {};
  
  status = M95_spi_ReadData( pObj, pData, TarAddr, PageSize );
  
  return status;
}

2. M95_spi_WritePage() will call M95_spi_WriteData()


int32_t M95_spi_WritePage( M95_Object_t *pObj, uint8_t * pData, const uint32_t TarAddr, const uint16_t PageSize,const uint16_t NByte)
{
  int32_t status = M95_OK;
  while( pObj->IO.IsReady( pObj->IO.Address ) != M95_OK ) {};
    
  status = M95_spi_WriteData(pObj, pData, TarAddr , PageSize, NByte );
  
  return status;
}

You can refer the already available function M95_TestData() from our example application.


Apart from this, we have also updated the following page ID functions:

1. M95_spi_ReadID ()
2. M95_spi_WriteID ()
3. M95_spi_LockStatus ()
4. M95_spi_LockID ()


Meanwhile, kindly let us know your application which you are working on for further support.

Thanks.

**Comment by escherstair** [comment]
Hello @tanujlokpal 
I see you closed the issue as completed, but I don't see any recent commit in the repo.
Can you clarify, please?

**Comment by tanujlokpal** [comment]
Hello @escherstair 

We have given the required code snippet in the comments above. The code will update in a future release.

Kindly let us know your specific application for further support.

Thanks.
