### ISSUE TITLE
m95p32 driver doesn't use the io api.

### ISSUE THREAD

**Issue by perencia-wc** [STMicroelectronics/X-CUBE-EEPRMA1#11]
The functions of `M95_IO_t `are never used, except for `Init `and `Deinit`. Instead, HAL calls are directly used. This complicates the use of the driver to integrate on other than ST micros.

**Comment by tanujlokpal** [comment]
Hello @perencia-wc,

Thank you for your comment. We are investigating.

Thanks.

**Comment by tanujlokpal** [comment]
Hello @perencia-wc,

Kindly checkout our latest release and do give your feedback!

Thanks.
