### ISSUE TITLE
Explanations of interfaces and usage would be helpful

### ISSUE THREAD

**Issue by MGehrmann** [STMicroelectronics/X-CUBE-EEPRMA1#2]
Good day,

An explanation of the use of this pack would be very helpful. While trying to understand the sample project, I came across several things that I do not understand.

This starts with the **inzilisieren**:

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/EEPRMA2/eeprma2_m95.c#L608-L640

what is "M95_RegisterBusIO" needed for here? 

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.c#L75-L93

Then > M95Drv[EEPRMA2_M95M04_0] = (M95_EEPROM_CommonDrv_t *)(void *)&M95_spi_Drv; < 

cast to another datatype which has exactly the same structure.

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.h#L130-L175

Furthermore, there are many  **commented functions**. Which are not found elsewhere in the program.

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.h#L188-L223

If I understand correctly the functions which are named in the doxygen comment as "M95xx_Private_Functions" are actually the interfaces which should be used by the program, right? 

But the example uses:

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/a3609d5034b0507a74424d75e580a251285a4f86/Drivers/BSP/Components/M95xx/m95xx.h#L183

It would be very helpful to get a simple example, possibly with only one EEPROM.

Is the project currently still being revised? in many places it looks as if it is in the middle of a rebuilding process.

**Comment by indars** [comment]
Good day,

Function pointer and multiple structure is part of our framework to support multiple EEPROM on single expansion boards (Both SPI and I2C interface). The framework (X-CUBE-EEPRMA1) is STM32CubeMX compliance therefore user can easily integrate driver from any other expansion/ STM32Nucleo board.

User can optimize the code for single EEPROM or as per there application. The commented lines of code is to maintain consistency across different EEPROM expansion boards. The dummy code shall be removed in the next releases.

Thanks,
BR,
Indar
