### ISSUE TITLE
Wrong documentation for M95_spi_IsDeviceReady

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/X-CUBE-EEPRMA1#9]
This is the documentation for M95_spi_IsDeviceReady function
https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/358e9b9e2f8b03370abc400b1464aedce63e29c6/Drivers/BSP/Components/M95xx/m95xx.c#L120-L124
Is refers to a `Trials` parameter, but the signature of the function doesn't have it
https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/358e9b9e2f8b03370abc400b1464aedce63e29c6/Drivers/BSP/Components/M95xx/m95xx.c#L125

From my perspective, what is not consistent is that for M24xx the signature seems to be
https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/358e9b9e2f8b03370abc400b1464aedce63e29c6/Drivers/BSP/Components/M24xx/m24xx.h#L110
with the `Trials` parameter,
instead for M95xx the signature is
https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/358e9b9e2f8b03370abc400b1464aedce63e29c6/Drivers/BSP/Components/M95xx/m95xx.h#L111
with one parameter only (no `Trials`)

Can someone fix this, please?

**Comment by tanujlokpal** [comment]
Hello @escherstair,

Reported concern is fixed in latest release.

Thanks.

**Comment by escherstair** [comment]
@tanujlokpal 
sorry, but I don't understand how and where it has been fixed.

**Comment by tanujlokpal** [comment]
@escherstair 

Kindly check:

https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/blob/9af4d0fc3be91a87582ac9acba55799c72dc4762/Drivers/BSP/Components/M95xx/m95xx.c#L126C1-L134C2

Also, please refer to latest V5.1.0 release here:
https://github.com/STMicroelectronics/X-CUBE-EEPRMA1/tree/V5.1.0

Thanks.
